### ISSUE TITLE
Issue with property table 

### ISSUE THREAD

**Issue by bsrinivasa** [osmlab/changeset-map#122]
Faced an issue with property table while reviewing this changeset in the changeset map. 
Changeset link: https://osmcha.mapbox.com/47079752/

cc: @ajithranka

**Comment by ajithranka** [comment]
Specifically, the properties table is empty when selecting a few newly created nodes.

http://osmlab.github.io/changeset-map/#47079752/node/4749632425
http://osmlab.github.io/changeset-map/#47079752/node/4749632422

**Comment by ajithranka** [comment]
**Reason**: [`propsDiff.js#L11-L13`](https://github.com/osmlab/changeset-map/blob/gh-pages/js/propsDiff.js#L11-L13) breaks because of duplicate features in the json.

http://s3.amazonaws.com/mapbox/real-changesets/production/47079752.json
Duplication for ids: 4749632422, 4749632423, 4749632424.

cc: @geohacker @batpad

**Comment by ajithranka** [comment]
Fixed.
