### ISSUE TITLE
Visualization not matching to the deleted elements

### ISSUE THREAD

**Issue by krishnanammala** [osmlab/changeset-map#52]
I came across one issue where the user is not deleting any feature, but the visualization of the changeset map shows the deletions.

Detected issue: [here](http://osmcha-django-staging.tilestream.net/39603567/).

![screen shot 2016-06-02 at 2 59 56 pm](https://cloud.githubusercontent.com/assets/17470597/15740512/c08211d2-28d2-11e6-85ec-42450f06bee1.png)

cc @batpad

**Comment by batpad** [comment]
cc @ajithranka 

So far:

 - The current code relying on the assumption that version numbers will increment allowing us to find old and new versions of a feature is obviously wrong, since we cannot expect the version number to increment for every change (when the node in a way has moved, for eg.)

 - Timestamp doesn't really seem to help.

 - Perhaps, we can traverse the nodes that are part of each way and find the one with the later version of a changed node?

Or .. ?

OR we just give up on trying to distinguish between old and new in these cases, and just show the modified feature.

**Comment by ajithranka** [comment]
I did some digging for this particular changeset with @ramyaragupathy and @geohacker and here are a couple of things that stand out.

The [changeset](http://www.openstreetmap.org/api/0.6/changeset/39596416) was closed within 4 seconds after being opened, which seems fine. This is not a case of the changeset being kept open for long time (`open=false`).

The particular [overpass query](https://overpass-cfn-staging.tilestream.net/api/interpreter?data=%5Bout:json%5D%5Badiff:%222016-05-27T12:51:21Z,%22,%222016-05-27T12:51:24Z%22%5D;(node(bbox)(changed);way(bbox)(changed););out%20meta%20geom(bbox);&bbox=77.4330782,23.233863,77.4355526,23.2363234) we are using right now shows that the way with id `30053996` has been modified but the version number, changeset id and timestamp are not updated.

```
{
  "type": "way",
  "id": 30053996,
  "timestamp": "2016-05-27T06:34:43Z",
  "version": 8,
  "changeset": 39596416,
  "user": "premkumar",
  "uid": 2901478,
 ...
  "nodes": [
    3168001696,
    331031748,
    331031538,
    331031461,
    331032384,
    3714581704,
    4210254727,
    331031423
  ],
  ...
}
```
The nodes have been moved around but the way is unchanged. Checking for the individual nodes shows that their individual version numbers have been updated.

```
{
  "type": "node",
  "id": 331031461,
  "lat": 23.2362018,
  "lon": 77.4330788,
  "timestamp": "2016-05-27T12:45:35Z",  <----------
  "version": 8,   <----------
  "changeset": 39603433,  <----------
  "user": "premkumar",
  "uid": 2901478
},
{
  "type": "node",
  "id": 331031461,
  "lat": 23.2362141,
  "lon": 77.4331191,
  "timestamp": "2016-05-27T12:51:23Z", <----------
  "version": 9,  <----------
  "changeset": 39603567, <----------
  "user": "premkumar",
  "uid": 2901478
}
```

We could run [the same query with the output format set to `xml`](https://overpass-cfn-staging.tilestream.net/api/interpreter?data=%5Bout:xml%5D%5Badiff:"2016-05-27T12:51:21Z,","2016-05-27T12:51:24Z"%5D;(node(bbox)(changed);way(bbox)(changed););out%20meta%20geom(bbox);&bbox=77.4330782,23.233863,77.4355526,23.2363234) and get a much cleaner result. The `xml` has an `<action type="*">` tag which mentions if the feature has been added, deleted or modified. In case of a modified feature, `<old>` and `<new>` tags give the old and new versions of the feature.

```
<action type="modify">
<old>
  <way id="30053996" version="8" timestamp="2016-05-27T06:34:43Z" changeset="39596416" uid="2901478" user="premkumar">
    <bounds minlat="23.2351082" minlon="77.4330788" maxlat="23.2371568" maxlon="77.4331612"/>
    <nd ref="3168001696" lat="23.2351082" lon="77.4331569"/>
    <nd ref="331031748" lat="23.2354573" lon="77.4331612"/>
    <nd ref="331031538" lat="23.2357275" lon="77.4331346"/>
    <nd ref="331031461" lat="23.2362018" lon="77.4330788"/>
    <nd ref="331032384" lat="23.2371568" lon="77.4330840"/>
    <nd ref="3714581704"/>
    <nd ref="4210254727"/>
    <nd ref="331031423"/>
    <tag k="highway" v="residential"/>
  </way>
</old>
<new>
  <way id="30053996" version="8" timestamp="2016-05-27T06:34:43Z" changeset="39596416" uid="2901478" user="premkumar">
    <bounds minlat="23.2351119" minlon="77.4330840" maxlat="23.2371568" maxlon="77.4331719"/>
    <nd ref="3168001696" lat="23.2351119" lon="77.4331629"/>
    <nd ref="331031748" lat="23.2354597" lon="77.4331719"/>
    <nd ref="331031538" lat="23.2357473" lon="77.4331587"/>
    <nd ref="331031461" lat="23.2362141" lon="77.4331191"/>
    <nd ref="331032384" lat="23.2371568" lon="77.4330840"/>
    <nd ref="3714581704"/>
    <nd ref="4210254727"/>
    <nd ref="331031423"/>
    <tag k="highway" v="residential"/>
  </way>
</new>
</action>
```

I think if we stick to the `json` output, in these cases we'll need to compare the version of individual nodes in a way (not just the feature geometry) to identify the old and new versions.

Otherwise, if possible, we could go with the xml output. I'm not sure though how much of a change that might be to the current code.

cc: @batpad @planemad

**Comment by mikelmaron** [comment]
Is modifying the JSON output an option? Could add a timestamp for when members of a way (or relation) were modified? @geohacker @batpad @ajithranka

**Comment by batpad** [comment]
There is a timestamp property @mikelmaron but there were various cases where the timestamp for both the versions of the feature would be the same.

Right now, if version and timestamp are both the same, the code traverses through all the nodes of each feature and figures out which feature is newer based on the version of its nodes. This, to me, is a totally acceptable solution.

I think modifying Overpass upstream is something we don't want to get into - and currently, the code we have works, so I'm not really seeing this as an issue. I can see some benefits of code clarity if we process the XML directly, but I also suspect we'll run into other issues - we can ticket the XMLification out, @ajithranka, but unless we're seeing it fixing something that's not fixable currently, I'd rather keep that for a refactor later if it really is going to provide some tangible benefit.

**Comment by mikelmaron** [comment]
Riiiight gotcha. Traversal sounds sane. You could probably also make some assumption about order of features in the collection, but feels fragile.
