### ISSUE TITLE
Nodes are not clickable

### ISSUE THREAD

**Issue by planemad** [osmlab/changeset-map#82]
Try to click on the Lima node to check the change. It is currently not clickable.

https://osmcha.mapbox.com/40650687/

cc @ajithranka @rasagy

**Comment by planemad** [comment]
It looks like deleted nodes are clickable, but not those modified or created.

**Comment by ajithranka** [comment]
The two modified nodes in Lima are part of a relation. Our overpass `adiff` query checks only for nodes and ways right now and not relations. That might be the reason why they don't have a feature diff.

But no diff for modified and created nodes is weird. I'll keep 🕵️ ing.

**Comment by planemad** [comment]
One more example: try clicking on any of the added POIs http://osmcha.mapbox.com/42299877/

**Comment by rasagy** [comment]
In our recent redesign of [untagged nodes](https://github.com/osmlab/changeset-map/issues/125#issuecomment-289665860), we switched to:
- Nodes with tags are clickable
- Nodes without tags but moved (geometry change) are clickable — this lets you highlight the before and after states
- Other nodes without tags (added, modified, deleted) are *not* clickable — default behavior is to select a way (if it is part of a way), otherwise do nothing.

Edge cases include deleting or adding isolated untagged nodes — this means that some nodes will not be clickable, like in https://osmlab.github.io/changeset-map/#47465701

While making all nodes clickable makes it harder to interact with the map at a lower zoom level, we’ll take that approach for now: this will be especially helpful once we have more links like feature-level links (#137).

cc @ajithranka @planemad @batpad @geohacker

**Comment by willemarcel** [comment]
@planemad @ajithranka can we close this issue?
